# Generated by Django 5.0.3 on 2024-07-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_scheduled',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
