# Generated by Django 5.0.3 on 2024-07-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_arrival_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_actual',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_estimated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_runway',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_actual',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_estimated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_runway',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
